# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
name: Goodments
tagline: Make money and do good.
title: Goodments - Make money and do good.
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Change the behaviour of corporations, through the power of investments.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://goodments.com" # the base hostname & protocol for your site
fb_app_id: '1007509392650454'


# Build settings
markdown: kramdown

exclude: []